### ISSUE TITLE
Allow to dismiss "out of date" message for some time

### ISSUE THREAD

**Issue by kamaradclimber** [scalameta/metals-languageclient#180]
**Describe the feature**

Allow user to dismiss "out of date" message for some time.

Currently the message:
```
You are running an out-of-date version of Metals. The latest version is 0.9.3, but you have configured a custom server version 0.7.5
```
is displayed every time I open neovim.
I use this version to be compatible with an old scala version.

**Comment by kamaradclimber** [comment]
Seems fair, I'll see what is blocking to use latest version of metal. Thanks for your input and feel free to close the issue if you prefer.

**Comment by ckipp01** [comment]
Seeing that it's been a bit of time and this hasn't come up again. I'm going to go ahead and close.

**Comment by kamaradclimber** [comment]
yes, thanks!
