### ISSUE TITLE
`child_process.spawn` + JVM on IPv6 Proxy doesn't work

### ISSUE THREAD

**Issue by siddhant3s** [scalameta/metals-languageclient#219]
The `fetchMetals` function uses `child_process.spawn*` to start a JVM to call `coursier` to fetch Metals. When we're behind a proxy, the `.jvmopts` allow us to set the `http.proxyHost=my_proxy_host` which is passed to the JVM and should be respected.

This works well when when `my_proxy_host` is an IPv4 host. If it's IPv6, things break: `coursier` isn't able to connect to the proxy. 

**Why this happens**: Due to a very obscure bug in the JVM. To quote the description

> A DESCRIPTION OF THE PROBLEM :
When a unix domain socket is bound to fd 0 of a JVM instance all IPv6 functionality is disabled. This for example occurs when the JVM is spawned by Node.js (see https://stackoverflow.com/questions/34108124/ip-addresses-of-network-interfaces-in-a-java-process-spawned-by-nodejs). 

So if your proxy is IPv6 only, this functionality doesn't work. And since this is the first step in setting up Metals, nothing else work.

**How to fix it**:  The fix is simple -- we need to pass `{stdio: ["ignore"]}` as an option to the `child_process.spawn` which fixes this issue. Since we don't interact with the stdin of the JVM and it's a short lived process, I think this is a reasonable change to add. 

Repro:
1. Setup an HTTP IPv6 proxy. Let's call it `my_proxy_host`
2. Either in the server properties on VSCode or in the `.jvmopts` add the following lines:
    ```
    -Djava.net.preferIPv4Stack=false
    -Djava.net.preferIPv6Addresses=true
    -Dhttp.proxyHost=my_proxy_host
    -Dhttp.proxyPort=8080
    ```
3. Now simply try starting VSCode after clearing your coursier cache.
4. Observed Behavior: VSCode extension fails to Download metals. 
5 Expected Behavior: VSCode extension should respect the proxy and download Metals.

Smaller Repro step:
1. Create the following program into a JAR file: https://gist.github.com/siddhant3s/3f843dd5f3f2fd30788dfb97e901397e and save it into `/tmp/javaget.jar`
2. Copy this small NodeJS script https://gist.github.com/siddhant3s/7cf5828231f60664e25011796fb70733 and save it to /tmp/node2java.js
3. Run this script `node /tmp/node2java.js`. 

You will see that the first call will not succeed while the second call will succeed.

## Fix
It's a simple one line fix which I have already tried and it succeed. The bug report also mentions the same fix.

**Comment by ckipp01** [comment]
Closed via https://github.com/scalameta/metals-languageclient/pull/220
